# Generated by Django 3.2.12 on 2023-07-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_auto_20230726_0746'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
