# Generated by Django 3.2.12 on 2023-07-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
