# Generated by Django 3.2.12 on 2023-07-27 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_customuser_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='domain',
        ),
    ]
